--borara dts

--DELETE 

select *
FROM msdb.dbo.sysdtspackages
WHERE name in (
'CARGUE_RAW_FLUJOS_SRV_FORWARD_458M_A',
'CARGUE_RAW_FLUJOS_SRV_POSICION_DIVISAS_458D',
'CARGUE_RAW_FLUJOS_SRV_POSICION_DIVISAS_458M_A',
'CARGUE_RAW_FLUJOS_SRV_TITULOS_458D',
'CARGUE_RAW_FLUJOS_SRV_TITULOS_458M_A',
'GENERA_SZENA_FORWARDS',
'GENERA_SZENA_FORWARDS_TITULOS',
'GENERA_SZENA_FX_OPCIONES',
'GENERA_SZENA_INTBCRIOS_REPOS',
'GENERA_SZENA_POSICIONES_DIVISAS',
'GENERA_SZENA_SWAPS',
'GENERA_SZENA_TITULOS_VALORES'
)