/****** Script for SelectTopNRows command from SSMS  ******/
SELECT x.[name] as dts
      ,(SELECT j.[name] FROM [msdb].[dbo].[sysjobs] j
        WHERE j.[job_id] = x.[jobid]) job
      ,x.[pasoid]
      ,x.[paso]

      , CASE
          WHEN (  x.[id] = x.[id_en_job] ) THEN 'iguales'
          ELSE 'diferentes' 
        END as comparacion

      , x.[id] as id_dts
      ,x.[id_en_job]
--      ,x.[comando]
FROM (
SELECT p.[name]
      ,p.[id]
      ,(SELECT top 1 [job_id] FROM [msdb].[dbo].[sysjobsteps] s
        WHERE s.command like ('%' + ltrim(rtrim(p.name)) +'" /G%')) as jobid
      ,(SELECT top 1 [step_id] FROM [msdb].[dbo].[sysjobsteps] s
        WHERE s.command like ('%' + ltrim(rtrim(p.name)) +'" /G%')) as pasoid
      ,(SELECT top 1 [step_name] FROM [msdb].[dbo].[sysjobsteps] s
        WHERE s.command like ('%' + ltrim(rtrim(p.name)) +'" /G%')) as paso
      ,(SELECT top 1 SUBSTRING ( [command], CHARINDEX ('{',[command])+1,36) FROM [msdb].[dbo].[sysjobsteps] s
        WHERE s.command like ('%' + ltrim(rtrim(p.name)) +'" /G%')) as id_en_job
      ,(SELECT top 1 [command] FROM [msdb].[dbo].[sysjobsteps] s
        WHERE s.command like ('%' + ltrim(rtrim(p.name)) +'" /G%')) as comando
  FROM [msdb].[dbo].[sysdtspackages] p

  WHERE
         p.createdate >= CONVERT (date, GETDATE()) -- '20140603'
  /*
   p.NAME IN ( 
  
 
  'CARGUE_CONTROL_FLUJOS_PRODUCTO',
'CARGUE_RAW_FLUJOS_ABK_CHA_458M',
'CARGUE_RAW_FLUJOS_OPEN_CARD_458M',
'CARGUE_RAW_FLUJOS_PHO_FOM_ORD_458M',
'CARGUE_RAW_FLUJOS_PHO_PASIVAS_458M',
'CARGUE_RAW_FLUJOS_PHO_ROT_458M',
'CARGUE_RAW_FLUJOS_REC_HUMANOS_458M',
'CARGUE_RAW_FLUJOS_KPL_FUT_458M',
'CARGUE_RAW_FLUJOS_KPL_FXO_458M',
'CARGUE_RAW_FLUJOS_SRV_FORWARD_458M',
'CARGUE_RAW_FLUJOS_SRV_TITULOS_458M',
'CARGUE_RAW_FLUJOS_PHO_CTBLE_CMATRIZ_458M',
'GENERA_FLUJOS_CONTABLES_CASA_MATRIZ',
'GENERA_FLUJOS_PASIVO_VISTA_CASA_MATRIZ',
'CARGUE_RAW_FLUJOS_ABK_CHA_458D',
'Etl CARGUE_BKT_RAW_FLUJOS_DIARIOS',
'CARGUE_RAW_FLUJOS_KPL_FUT_458D',
'CARGUE_RAW_FLUJOS_KPL_FXO_458D',
'CARGUE_RAW_FLUJOS_KPL_SWP_458D',
'CARGUE_RAW_FLUJOS_LEASING_458D',
'CARGUE_RAW_FLUJOS_OPEN_CARD_458D',
'CARGUE_RAW_FLUJOS_PHO_FOM_ORD_458D',
'CARGUE_RAW_FLUJOS_PHO_PASIVAS_458D',
'CARGUE_RAW_FLUJOS_PHO_ROT_458D',
'CARGUE_RAW_FLUJOS_REC_HUMANOS_458D',
'CARGUE_RAW_FLUJOS_SRV_FORWARD_458D',
'CARGUE_RAW_FLUJOS_SRV_TITULOS_458D',
'CARGUE_RAW_FLUJOS_PHO_CTBLE_CMATRIZ_458D',
'GENERA_FLUJOS_CONTABLES_CM_SZENA_D',
'GENERA_SZENA_ACT_PAS_PLAZO',
'GENERA_SZENA_BONOS',
'GENERA_SZENA_CDTS',
'GENERA_SZENA_CREDITOS_ACTIVO',
'GENERA_SZENA_CREDITOS_PASIVOS',
'GENERA_SZENA_DERIVADOS',
'GENERA_SZENA_FORWARDS',
'GENERA_SZENA_FORWARDS_TITULOS',
'GENERA_SZENA_FX_OPCIONES',
'GENERA_SZENA_INTBCRIOS_REPOS',
'GENERA_SZENA_PASIVO_VISTA',
'GENERA_SZENA_SWAPS',
'GENERA_SZENA_TITULOS_VALORES',
'CARGUE_RAW_FLUJOS_RCONTROL',
'GENERA_FLUJOS_CONTABLES_CM_SZENA_D',
'GENERA_FLUJOS_CONTABLES_CM_SZENA_D',
'GENERA_FLUJOS_CONTABLES_CM_SZENA_D',
'GENERA_FLUJOS_CONTABLES_CM_SZENA_D'

  --'CARGUE_SRV_RAW_DIVISAS_SPOT_ACT_PAS'
  
  -- aqui un corte 
  ,
'CARGUE_RAW_FLUJOS_PHO_PASIVAS_458M',
'CARGUE_RAW_FLUJOS_PHO_ROT_458M',
'DEPURAR_POBLAR_PTR_PRECIOS_TRANSFERENCIA_F2',
'POBLAR_LEA_PRESUPUESTO_exp',
'POBLAR_LEA_PRESUPUESTO_PARCIAL',
'CARGUE_ACT_MANUAL_FLUJOS',
'CARGUE_CLA_INFORME_SUPER',

'CARGUE_CONTROL_FLUJOS_PRODUCTO',
'CARGUE_RAW_FLUJOS_ABK_CHA_458M',
'CARGUE_RAW_FLUJOS_PHO_FOM_ORD_458M',
'CARGUE_RAW_FLUJOS_AFC_458M',

'CARGUE_RAW_FLUJOS_KPL_SWP_458M',
'CARGUE_RAW_FLUJOS_SRV_TITULOS_458M',
'GEN_FLUJOS_CUADRE_CONTABLE_PRODS_VPO',
'GEN_FLUJOS_CUADRE_CONTABLE_PRODS_VPR',

'GENERA_FLUJOS_ACTIVO_PASIVO_CASA_MATRIZ',

'GENERA_FLUJOS_AP_DEF_CASA_MATRIZ',
'GENERA_FLUJOS_CONTABLES_CASA_MATRIZ'
*/
--)

) x
order by 5 desc
--ORDER BY x.NAME ASC

/*


SELECT top 1 CHARINDEX ( s.[command] ,'{',1) FROM [msdb].[dbo].[sysjobsteps] s
SELECT top 1  [command] FROM [msdb].[dbo].[sysjobsteps] s
        WHERE s.command like ('%' + ltrim(rtrim('0A6F52C3-AE8E-4794-A3C2-18D3A8F90D15')) +'%')
        
 
DTSRun /S "BOINFSQL3" /N "CARGUE_RAW_FLUJOS_PHO_FOM_ORD_458M" /G "{110AFD9C-CC47-45E5-ABC7-55A679DA367B}" /L "D:\Cargue\log\CARGUE_RAW_FLUJOS_PHO_FOM_ORD_458M.txt" /W "0" /E     
        
        
0A6F52C3-AE8E-4794-A3C2-18D3A8F90D15
4DBD442D-7D65-495E-B1AE-701EEE59D2D4
FD1F1C81-BCBB-4613-B63B-79C5C4D3E954
51933917-9ACF-4E19-8CB2-8537233386FE
316A9FBA-A0CC-464B-818D-B361F9456E60
35971A93-CFBC-4753-ACCF-D6FBC3BCD0CA
*/
